blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('', views.home, name='all_blogs'),
    path('<int:blog_id>', views.details, name='details'),
    ]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class BlogModel(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class PortfolioModel(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogModel

# Create your views here.
def home(request):
    #blogs = BlogModel.objects.order_by('-date')[:5]
    blogs = BlogModel.objects.order_by('-date')
    return render(request, 'blog/home.html', {'blogs': blogs})


def details(request, blog_id):
    blog = get_object_or_404(BlogModel, pk= blog_id)
    return render(request, 'blog/details.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import PortfolioModel


def home(request):
    projects = PortfolioModel.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/details.html
{% extends 'portfolio/base.html' %}
{% block content %}
<h2>Blog Title:-{{blog.title}}</h2>
<p>{{blog.description|safe}}/</p>
{% endblock %}

blog/templates/blog/home.html
{% extends 'portfolio/base.html' %}
{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<div class="container text-center"><h3>Blogs</h3>

    <h3> Total available blog{{blogs.count|pluralize}}-{{blogs.count}}</h3>
    {% for blog in blogs %}

    <hr style="height:2px;background-color:#10453B;border:none;" noshade />
    <a href ="{% url 'blog:details' blog.id%}"><h4><i>{{blog.title}}</i></h4></a>
    <b>{{blog.date|date:'M dS Y'|upper}}</b>
    <p>{{blog.description| striptags| truncatechars:100}}</p>

    <hr style="height:2px;background-color:#10453B;border:none;" noshade />
    {% endfor %}

</div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

{% block content %} {% endblock %}

</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% load static %}

<br>

<div class="container">
    <div class="row">
        <div class="col-4">
            <img src="{% static 'portfolio/photonature.jpeg' %}" width="150px" height="100px">
        </div>
        <div class="col-4">
            <h2>Portfolio-page &#x1F604</h2>
        </div>
        <div class="col-4">
            <a href="{% url 'blog:all_blogs'%}">Blog</a>
        </div>
    </div>
    <hr style="height:2px;background-color:#10453B;border:none;" noshade/>
    {% for project in projects%}
    <h3>{{project.title}}</h3>
    <p>{{project.description}}</p>
    <img src="{{project.image.url}}" height="50%" width="60%"/>
    <br>
    <br>
    {% if project.url%}
    <a href="{{project.url}}">Link</a>
    {%endif%}
    <hr style="height:2px;background-color:#10453B;border:none;" noshade/>
    {%endfor%}

</div>

{% endblock %}